/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libarysystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class ViewBooks extends javax.swing.JFrame {
     String[] heading={"ID","Categories","Name","Author","Publisher","Value($)","pdf"};
    String[][] data;
    DataBaseConnection db=new DataBaseConnection();
    public ViewBooks() throws ClassNotFoundException {
        initComponents();
         try {
             data=db.getAllBooks();
         } catch (SQLException ex) {
             Logger.getLogger(ViewBooks.class.getName()).log(Level.SEVERE, null, ex);
         }
        tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbpanel = new javax.swing.JPanel();
        rball = new javax.swing.JRadioButton();
        rbit = new javax.swing.JRadioButton();
        rbm = new javax.swing.JRadioButton();
        rbc = new javax.swing.JRadioButton();
        tbpanel = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnpanel = new javax.swing.JPanel();
        btnview = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbpanel.setBackground(new java.awt.Color(51, 51, 255));

        buttonGroup1.add(rball);
        rball.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rball.setForeground(java.awt.Color.blue);
        rball.setText("All Categories");
        rball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rballActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbit);
        rbit.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbit.setForeground(java.awt.Color.blue);
        rbit.setText("IT Books");

        buttonGroup1.add(rbm);
        rbm.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbm.setForeground(java.awt.Color.blue);
        rbm.setText("Magazine");
        rbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbc);
        rbc.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbc.setForeground(java.awt.Color.blue);
        rbc.setText("Cartoon");
        rbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rbpanelLayout = new javax.swing.GroupLayout(rbpanel);
        rbpanel.setLayout(rbpanelLayout);
        rbpanelLayout.setHorizontalGroup(
            rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rbpanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rball)
                    .addComponent(rbc))
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rbpanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(rbm))
                    .addGroup(rbpanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(rbit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rbpanelLayout.setVerticalGroup(
            rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rbpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rball)
                    .addComponent(rbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbc)
                    .addComponent(rbm)))
        );

        tbpanel.setBackground(new java.awt.Color(153, 153, 255));
        tbpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tbpanel.setViewportView(tb);

        javax.swing.GroupLayout btnpanelLayout = new javax.swing.GroupLayout(btnpanel);
        btnpanel.setLayout(btnpanelLayout);
        btnpanelLayout.setHorizontalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        btnpanelLayout.setVerticalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        btnview.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        btnview.setForeground(java.awt.Color.blue);
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnclose.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        btnclose.setForeground(java.awt.Color.blue);
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnview)
                .addGap(106, 106, 106)
                .addComponent(btnclose)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(btnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclose)
                    .addComponent(btnview))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(btnpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rballActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rballActionPerformed

    private void rbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmActionPerformed

    private void rbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcActionPerformed

    private void tbpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpanelAncestorAdded

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        String Categories="";
        if(rball.isSelected())
        Categories="AllCategories";
        if(rbit.isSelected())
        Categories="ITBooks";
        if(rbc.isSelected())
       Categories="Cartoon";
        if(rbm.isSelected())
        Categories="Magazine";
        
        tbpanel.removeAll();
        if(Categories.equals("AllCategories"))
        {
            try {
                data=db.getAllBooks();
                tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
                tbpanel.setViewportView(tb);
                javax.swing.GroupLayout tbpanelLayout = new javax.swing.GroupLayout(tbpanel);
                tbpanel.setLayout(tbpanelLayout);
                tbpanelLayout.setHorizontalGroup(
                    tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );
                tbpanelLayout.setVerticalGroup(
                    tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                );
            } catch (ClassNotFoundException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            } catch (SQLException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        }
        else
        {
            tbpanel.removeAll();
            try {
                data=db.getBooksbyC(Categories);
                tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
                tbpanel.setViewportView(tb);
                javax.swing.GroupLayout tbpanelLayout = new javax.swing.GroupLayout(tbpanel);
                tbpanel.setLayout(tbpanelLayout);
                tbpanelLayout.setHorizontalGroup(
                    tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );
                tbpanelLayout.setVerticalGroup(
                    tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                );
            } catch (ClassNotFoundException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            } catch (SQLException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewBooks().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewBooks.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rball;
    private javax.swing.JRadioButton rbc;
    private javax.swing.JRadioButton rbit;
    private javax.swing.JRadioButton rbm;
    private javax.swing.JPanel rbpanel;
    private javax.swing.JTable tb;
    private javax.swing.JScrollPane tbpanel;
    // End of variables declaration//GEN-END:variables
}
